### ISSUE TITLE
Styles for attached files

### ISSUE THREAD

**Issue by lmcruza** [lmcruza/fld#129]
It should be like this

![image](https://cloud.githubusercontent.com/assets/5748013/23297394/aa423bd0-fa79-11e6-93b6-1e1f8cc1707c.png)

but it looks like this

![image](https://cloud.githubusercontent.com/assets/5748013/23297411/b56533aa-fa79-11e6-9bb6-e910e2ea6c2e.png)

**Comment by valger10** [comment]
Luis Manuel fixed this.
