### ISSUE TITLE
Text size should be smaller for mobile in "portada-matriz-imagenes-con-link" template

### ISSUE THREAD

**Issue by lmcruza** [lmcruza/fld#130]
Text size (header and paragraph) should be smaller as text is cut in mobile.

There is no specific size so you have to try different sizes until text is properly shown.

![image](https://cloud.githubusercontent.com/assets/5748013/23405508/d76adb28-fdba-11e6-9e85-28760de8e480.png)

**Comment by lmcruza** [comment]
You should also check size on image for the rest of contents where you can find text on image.

**Comment by valger10** [comment]
fixed
