### ISSUE TITLE
Overlapping in text and icon for accordion in mobile. Check "contenido-interior-acordeon" template

### ISSUE THREAD

**Issue by lmcruza** [lmcruza/fld#132]
Text and accordion icons produce overlapping.

![image](https://cloud.githubusercontent.com/assets/5748013/23405728/ee4ab02e-fdbb-11e6-9a21-5857684daecb.png)

**Comment by lmcruza** [comment]
Check https://www.fundacionlineadirecta.org/conocenos in mobile

**Comment by valger10** [comment]
fixed
