### ISSUE TITLE
Styles for "contenido-texto-imagen-flotante" template

### ISSUE THREAD

**Issue by lmcruza** [lmcruza/fld#48]
This new structure could be use for most common contents with repeated paragraphs with or without image. As a brief description:

1. Use similar styles as in "contenido-interior-texto" or "contenido-interior-acordeon".
2. Image alignment can be "left", "right" and "center". Something like http://www.inmotionhosting.com/support/edu/website-design/insert-images-website/align-float-images-css

**Comment by valger10** [comment]
fixed

**Comment by lmcruza** [comment]
It is not working.

**Comment by lmcruza** [comment]
Sorry, a cache problem testing it.
