### ISSUE TITLE
Modify styles for "portada-imagen-y-video-pantalla-completa-con-link" structure

### ISSUE THREAD

**Issue by lmcruza** [lmcruza/fld#61]
- Header and paragraph should be below "play" button.
- Header and paragraph should be hidden at the same time than the image. Now they are shown on the video too.

**Comment by lmcruza** [comment]
- If textInWhite is true then text in button is not visible in button.
- play button does not work at all. No javascript error is shown but nothing happens.

no more tests can be done

**Comment by valger10** [comment]
fixed
