### ISSUE TITLE
Full screen images

### ISSUE THREAD

**Issue by lmcruza** [lmcruza/fld#99]
Templates affected:
- contenido-carrusel
- contenido-imagen-pantalla-completa-con-texto-link
- contenido-interior-acordeon
- contenido-interior-texto
- contenido-texto-imagen-flotante
- contenido-patronato

**Comment by lmcruza** [comment]
Inserted code wrapping img element:

		<div class="img-wpr">
			<img src="..." />
		</div>

**Comment by valger10** [comment]
Fixed
